In [9]:
from pandas import Series, DataFrame
import numpy as np

In [2]:
import pandas as pd

In [71]:
obj = Series([4,7,-5,3])

In [72]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [73]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [74]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [75]:
obj2 = Series([4,7,-5,3], index=['d','b','a','c'])

In [76]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [77]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [78]:
obj2[obj2 >0]

d    4
b    7
c    3
dtype: int64

In [79]:
obj2 *2

d     8
b    14
a   -10
c     6
dtype: int64

In [80]:
import numpy as np

In [81]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [82]:
'b' in obj2

True

In [83]:
'e' in obj2

False

In [84]:
sdata = {'Ohio' :35000, 'Texas' : 71000, 'Oregon' :16000, 'Utah' : 5000}

In [85]:
obj3 = Series(sdata)

In [86]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [87]:
states = ['California', 'Ohio', 'Texas', 'Oregon']

In [88]:
obj4 = Series(sdata,index = states)

In [89]:
obj4

California        NaN
Ohio          35000.0
Texas         71000.0
Oregon        16000.0
dtype: float64

In [90]:
pd.isnull(obj4)

California     True
Ohio          False
Texas         False
Oregon        False
dtype: bool

In [91]:
pd.notnull(obj4)

California    False
Ohio           True
Texas          True
Oregon         True
dtype: bool

In [92]:
obj4.notnull

<bound method NDFrame.notnull of California        NaN
Ohio          35000.0
Texas         71000.0
Oregon        16000.0
dtype: float64>

In [93]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [94]:
obj4

California        NaN
Ohio          35000.0
Texas         71000.0
Oregon        16000.0
dtype: float64

In [95]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [96]:
obj4.name = 'population'

In [97]:
obj4.index.name ='state'

In [98]:
obj4

state
California        NaN
Ohio          35000.0
Texas         71000.0
Oregon        16000.0
Name: population, dtype: float64

In [99]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [100]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [101]:
data = {'state' : ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
       'year' : [2000, 2001, 2002, 2001, 2002],
       'pop' : [1.5, 1.7, 3.6, 2.4, 2.9]}

In [102]:
frame = DataFrame(data)

In [103]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [104]:
DataFrame(data, columns =['year','state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [105]:
frame2 = DataFrame(data, columns =['year','state', 'pop', 'debt'],
                  index=['one', 'two', 'three', 'four', 'five'])

In [106]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [107]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [108]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [109]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [110]:
frame2['debt'] = 16.5

In [111]:
frame2['debt'] = np.arange(5.)

In [112]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [113]:
val = Series([-1.2, -1.5, -1.7], index= ['one', 'two', 'three'])

In [114]:
frame2.debt = val

In [115]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  -1.2
two    2001    Ohio  1.7  -1.5
three  2002    Ohio  3.6  -1.7
four   2001  Nevada  2.4   NaN
five   2002  Nevada  2.9   NaN

In [116]:
frame2['eastern'] = frame2.state == 'Ohio'

In [117]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5  -1.2     True
two    2001    Ohio  1.7  -1.5     True
three  2002    Ohio  3.6  -1.7     True
four   2001  Nevada  2.4   NaN    False
five   2002  Nevada  2.9   NaN    False

In [118]:
del frame2['eastern']

In [119]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [120]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio' : {2000: 1.5, 2001:1.7, 2002:3.6}}

In [121]:
frame3 = DataFrame(pop)

In [122]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [123]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [124]:
DataFrame(pop, index = [2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [125]:
pdata = {'Ohio' : frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}

In [126]:
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [127]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [128]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [129]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [130]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [131]:
frame2.values

array([[2000, 'Ohio', 1.5, -1.2],
       [2001, 'Ohio', 1.7, -1.5],
       [2002, 'Ohio', 3.6, -1.7],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan]], dtype=object)

In [132]:
obj = Series(range(3), index=['a', 'b', 'c'])

In [133]:
index = obj.index

In [134]:
index

Index(['a', 'b', 'c'], dtype='object')

In [135]:
index[1:]

Index(['b', 'c'], dtype='object')

In [136]:
index[1] ='d'

TypeError: Index does not support mutable operations

In [141]:
index = pd.Index(np.arange(3))

In [142]:
obj2 = Series([1.5, -2.5, 0], index=index)

In [143]:
obj2.index is index

True

In [144]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [145]:
'Ohio' in frame3.columns

True

In [146]:
2003 in frame3.index

False

In [147]:
obj = Series([4.5, 7.2, -5.3, 3.6], index =['d', 'b', 'a', 'c'])

In [148]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [149]:
obj2 = obj.reindex(['a','b', 'c', 'd', 'e'])

In [150]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [151]:
obj2 = obj.reindex(['a','b', 'c', 'd', 'e'], fill_value = 0)

In [152]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [153]:
obj3 = Series(['blue', 'purple', 'yellow'], index=[0,2,4])

In [154]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [155]:
frame = DataFrame(np.arange(9).reshape(3,3), index=['a','c','d'],
                 columns=['Ohio', 'Texas', 'California'])

In [156]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [157]:
frame2 = frame.reindex(['a', 'b', 'c','d'])

In [158]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [159]:
states =['Texas', 'Utah', 'California']

In [160]:
frame.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [161]:
obj = Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [162]:
obj['b']

1.0

In [163]:
obj[1]

1.0

In [164]:
obj[2:]

c    2.0
d    3.0
dtype: float64

In [165]:
obj['b':'c'] = 5

In [166]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [167]:
data = DataFrame(np.arange(16).reshape(4,4),
                index =['Ohio', 'Colorado', 'Utah', 'New York'],
                columns =['one', 'two', 'three', 'four'])

In [168]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [169]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [170]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [171]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [137]:
data

{'pop': [1.5, 1.7, 3.6, 2.4, 2.9],
 'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002]}

In [173]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [140]:
data[data < 5]=0

TypeError: '<' not supported between instances of 'dict' and 'int'

In [ ]:
data.ix[['Colorado', 'Utah'], [4,1,2]]

In [ ]:
help(pandas)

In [3]:
s1 = Series([7.3, -2.5, 3.4, 1.5], index=['a','c', 'd', 'e'])

In [4]:
s2 = Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f','g'])

In [5]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [6]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [7]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [10]:
df1 = DataFrame(np.arange(9.).reshape(3,3), columns=list('bcd'),
               index=['Ohio', 'Texas', 'Colorado'])

In [11]:
df2 = DataFrame(np.arange(12.).reshape(4,3), columns=list('bce'),
               index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [12]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [13]:
df2

b     c     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [14]:
df1 + df2

b     c   d   e
Colorado  NaN   NaN NaN NaN
Ohio      3.0   5.0 NaN NaN
Oregon    NaN   NaN NaN NaN
Texas     9.0  11.0 NaN NaN
Utah      NaN   NaN NaN NaN

In [15]:
df1 = DataFrame(np.arange(12.).reshape(3,4), columns=list('abcd'))

In [16]:
df2 = DataFrame(np.arange(20.).reshape(4,5), columns=list('abcde'))

In [17]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [18]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [19]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [20]:
df1.add(df2, fill_value=0)


a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [22]:
df1.reindex(columns=df2.columns, fill_value=0)


a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [23]:
arr = np.arange(12.).reshape(3,4)


In [24]:
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [25]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [26]:
arr - arr[0]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [27]:
frame = DataFrame(np.arange(12.).reshape(4,3), columns=list('bde'),
               index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [28]:
series = frame.iloc[0]

In [29]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [30]:
series


b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [31]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [33]:
series2 = Series(range(3), index=['b', 'e','f'])

In [34]:
frame + series

b     d     e
Utah    0.0   2.0   4.0
Ohio    3.0   5.0   7.0
Texas   6.0   8.0  10.0
Oregon  9.0  11.0  13.0

In [36]:
series3 = frame['d']

In [37]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [38]:
series3


Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [39]:
frame.sub(series3,axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [42]:
frame = DataFrame(np.random.randn(4,3), columns=list('bde'),
               index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [43]:
frame

b         d         e
Utah   -0.798071  0.939287  0.973885
Ohio    0.254492  0.257705  0.373031
Texas   1.132313 -1.869444 -1.418344
Oregon -0.599173 -0.168586  1.348039

In [44]:
np.abs(frame)

b         d         e
Utah    0.798071  0.939287  0.973885
Ohio    0.254492  0.257705  0.373031
Texas   1.132313  1.869444  1.418344
Oregon  0.599173  0.168586  1.348039

In [45]:
f= lambda x: x.max() - x.min()


In [46]:
frame.apply(f)

b    1.930383
d    2.808731
e    2.766383
dtype: float64

In [47]:
frame.apply(f, axis=1)

Utah      1.771956
Ohio      0.118539
Texas     3.001757
Oregon    1.947212
dtype: float64

In [48]:
frame

b         d         e
Utah   -0.798071  0.939287  0.973885
Ohio    0.254492  0.257705  0.373031
Texas   1.132313 -1.869444 -1.418344
Oregon -0.599173 -0.168586  1.348039

In [ ]:
page 129